version: "3"

services:
  db:
    image: postgres
    container_name: postgres-fastfeet
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    restart: always

  mongo:
    image: mongo
    container_name: mongo-fastfeet
    env_file:
      - ./.env
    ports:
      - ${MONGO_PORT}:27017
    restart: always

  redis:
    image: redis
    container_name: redis-fastfeet
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:6379
    restart: always

  api:
    image: api-fastfeet
    container_name: api-fastfeet
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - mongo
      - redis
    restart: always
    stdin_open: true
    tty: true